---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: {{ include "elasticagent.fullname" . }}
  labels:
    {{- include "elasticagent.labels" $ | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: basic
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "An Elastic Agent version is required" .Values.version }}
  {{- $esRef := or ((.Values.spec).elasticsearchRef) (.Values.elasticsearchRef) }}
  {{- if not ($esRef).name }}
  {{ fail "An elasticsearchRef is required" }}
  {{- end }}
  elasticsearchRef:
  {{- toYaml $esRef | nindent 4 }}
  {{- with or ((.Values.spec).image) (.Values.image) }}
  image: {{ . }}
  {{- end }}
  {{- $config := or ((.Values.spec).config) (.Values.config) }}
  {{- $configRef := or ((.Values.spec).configRef) (.Values.configRef) }}
  {{- if and $config $configRef }}
  {{ fail "At most one of config or configRef can be specified" }}
  {{- end }}
  {{- with $config }}
  config:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $configRef }}
  configRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with or ((.Values.spec).secureSettings) (.Values.secureSettings) }}
  secureSettings:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with or ((.Values.spec).serviceAccount) (.Values.serviceAccount) }}
  serviceAccountName: {{ .name }}
  {{- end }}
  {{- $ds := or (hasKey (.Values.spec) "daemonSet") (hasKey .Values "daemonSet") }}
  {{- $deploy := or (hasKey (.Values.spec) "deployment") (hasKey .Values "deployment") }}
  {{- $sts := or (hasKey (.Values.spec) "statefulSet") (hasKey .Values "statefulSet") }}
  {{- if and (not $ds) (not $deploy) (not $sts) }}
  {{ fail "At least one of daemonSet or deployment or statefulSet is required" }}
  {{- end }}
  {{- if $ds }}
  daemonSet:
    {{- if not (or ((.Values.spec).daemonSet) (.Values.daemonSet)) }}
    {}
    {{- else }}
    {{- toYaml (or ((.Values.spec).daemonSet) (.Values.daemonSet)) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $deploy }}
  deployment:
    {{- if not (or ((.Values.spec).deployment) (.Values.deployment)) }}
    {}
    {{- else }}
    {{- toYaml (or ((.Values.spec).deployment) (.Values.deployment)) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $sts }}
  statefulSet:
    {{- if not (or ((.Values.spec).statefulSet) (.Values.statefulSet)) }}
    {}
    {{- else }}
    {{- toYaml (or ((.Values.spec).statefulSet) (.Values.statefulSet)) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- with or ((.Values.spec).revisionHistoryLimit) (.Values.revisionHistoryLimit) }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with or ((.Values.spec).http) (.Values.http) }}
  http:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with or ((.Values.spec).mode) (.Values.mode) }}
  mode: {{ . }}
  {{- end }}
  {{- with or ((.Values.spec).fleetServerEnabled) (.Values.fleetServerEnabled) }}
  fleetServerEnabled: {{ . }}
  {{- end }}
  {{- with or ((.Values.spec).policyID) (.Values.policyID) }}
  policyID: {{ . }}
  {{- end }}
  {{- with or ((.Values.spec).kibanaRef) (.Values.kibanaRef) }}
  kibanaRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with or ((.Values.spec).fleetServerRef) (.Values.fleetServerRef) }}
  fleetServerRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
